# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGg3dbcBz0201vDgTiuViiAM2XHtybpD
"""

import pandas as pd

# Google Sheet ID and GID for the specific sheet
sheet_id = '1l7r7M1mD0ZFGRXkuQ9aoXttXnFEREpOiYyTab3tA-9U'
gid = '1978751252'

# Construct the direct CSV export URL
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}'

# Read the data into a DataFrame
df_rideflow = pd.read_csv(url)

print(df_rideflow.head())

df_no_missing = df_rideflow.dropna()
display(df_no_missing)

import numpy as np

print("Missing values before handling:")
print(df_rideflow.isnull().sum())

# Impute numerical columns with their mean
for col in df_rideflow.select_dtypes(include=np.number).columns:
    if df_rideflow[col].isnull().any():
        df_rideflow[col].fillna(df_rideflow[col].mean(), inplace=True)

# Impute categorical/object columns with their mode
for col in df_rideflow.select_dtypes(include='object').columns:
    if df_rideflow[col].isnull().any():
        df_rideflow[col].fillna(df_rideflow[col].mode()[0], inplace=True)

print("\nMissing values after handling:")
print(df_rideflow.isnull().sum())

df_rideflow

!pip install streamlit pyngrok py-cpuinfo fastapi uvicorn python-multipart
!pip install -q streamlit-folium geopy
# To run streamlit in Colab, we use localtunnel or similar
!npm install -g localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import LSTM, Dense
# 
# # --- PHASE 1: DATA FOUNDATION ---
# @st.cache_data
# def load_ride_data():
#     np.random.seed(42)
#     rows = 1000
#     # Following the dataset requirements (NYC Taxi/Synthetic OLA)
#     data = {
#         'timestamp': pd.date_range(start='2026-01-01', periods=rows, freq='H'),
#         'pickup_location': np.random.choice(['Zone A', 'Zone B', 'Zone C', 'Zone D'], rows),
#         'ride_count': np.random.randint(50, 250, rows),
#         'available_drivers': np.random.randint(40, 200, rows),
#         'traffic_level': np.random.uniform(1, 5, rows),
#         'fare_price': np.random.uniform(100, 500, rows),
#         'ride_status': np.random.choice([0, 1], rows, p=[0.8, 0.2]) # 0=Completed, 1=Cancelled
#     }
#     df = pd.DataFrame(data)
#     # Feature Extraction (Phase 1 guidelines)
#     df['hour'] = df['timestamp'].dt.hour
#     df['day'] = df['timestamp'].dt.dayofweek
#     df['is_weekend'] = df['day'].map(lambda x: 1 if x >= 5 else 0)
#     return df
# 
# df = load_ride_data()
# 
# # --- MODULE 1: MACHINE LEARNING MODELS ---
# def train_ml_models(data):
#     # Encoding categorical zones
#     X = pd.get_dummies(data[['hour', 'day', 'is_weekend', 'pickup_location']])
# 
#     # Use Case 1: Demand Prediction
#     model_demand = RandomForestRegressor(n_estimators=50).fit(X, data['ride_count'])
# 
#     # Use Case 2: Supply Prediction
#     model_supply = RandomForestRegressor(n_estimators=50).fit(X, data['available_drivers'])
# 
#     # Use Case 4: Cancellation Prediction
#     X_cancel = data[['ride_count', 'available_drivers', 'traffic_level']]
#     model_cancel = RandomForestClassifier().fit(X_cancel, data['ride_status'])
# 
#     return model_demand, model_supply, model_cancel, X.columns
# 
# m_demand, m_supply, m_cancel, feat_cols = train_ml_models(df)
# 
# # --- STREAMLIT UI ---
# st.set_page_config(page_title="RideFlow AI", layout="wide")
# st.title("🚖 RideFlow AI Dashboard")
# 
# # Sidebar inputs
# st.sidebar.header("Real-time Inputs")
# input_hour = st.sidebar.slider("Hour of Day", 0, 23, 12)
# input_zone = st.sidebar.selectbox("Select Zone", ['Zone A', 'Zone B', 'Zone C', 'Zone D'])
# 
# # Prepare prediction row
# pred_row = pd.DataFrame(columns=feat_cols)
# pred_row.loc[0] = 0
# pred_row['hour'] = input_hour
# if f'pickup_location_{input_zone}' in feat_cols:
#     pred_row[f'pickup_location_{input_zone}'] = 1
# 
# # Execute Predictions
# p_demand = m_demand.predict(pred_row)[0]
# p_supply = m_supply.predict(pred_row)[0]
# 
# # --- MODULE 1 (USE CASE 3): DYNAMIC PRICING LOGIC ---
# # Logical correctness is prioritized over perfect accuracy per guidelines
# gap = p_demand - p_supply
# surge = np.clip(1.0 + (gap / 100), 1.0, 3.0)
# final_price = 300 * surge
# 
# # --- DASHBOARD LAYOUT ---
# c1, c2, c3 = st.columns(3)
# with c1:
#     st.metric("Predicted Demand", f"{int(p_demand)} Rides")
# with c2:
#     st.metric("Predicted Supply", f"{int(p_supply)} Drivers")
# with c3:
#     st.metric("Surge Multiplier", f"{surge:.2f}x", delta=f"{surge-1:.2f}")
#     st.success(f"Final Dynamic Price: ₹{final_price:.2f}")
# 
# # Cancellation Risk
# cancel_prob = m_cancel.predict_proba([[p_demand, p_supply, 3.0]])[0][1]
# st.write(f"**Cancellation Risk Probability:** {cancel_prob:.2%}")
# 
# # Visualizing Hotspots (Module 2, Use Case 7)
# st.divider()
# st.subheader("Demand Hotspot Analysis")
# fig = px.density_heatmap(df, x="hour", y="pickup_location", z="ride_count")
# st.plotly_chart(fig, use_container_width=True)

!pip install -q streamlit

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501 & curl ipv4.icanhazip.com

